runtime: python39  # Specify the Python runtime version

handlers:
- url: /static
  static_dir: static/  # Path to your static files directory

- url: /.*
  script: auto  # This tells App Engine to route all requests to your Django application
